### PR TITLE
Added True Random Numbers Generation (TRNG) functions

### PR DESCRIPTION
**Pull request by Kongduino**
The SX127x series of LoRa chips has a register that can be used for True Random Numbers Generation, ie _RssiWideband_, `0x2C`. I added functions for this, based on my [Arduino Library](https://github.com/Kongduino/LoRandom). The LoRa chip needs to be set up in a precise way, in continuous mode, which is done by `setupLoRandom()`. Then and then only can `getRandomNumber()` be called to get an 8-bit random number. When done, you need to reset the LoRa chip to its previous state, with `resetLoRa()`.

Should you need more than one byte – and it's easier to get a whole bunch of random bytes at once anyway – `stockupRandom(count = 256)` does everything for you.

### CODE REVIEW

**Comment by hwreverse** [comment]
What actual physical principle is used as a base for the TRNG ?

**Comment by Kongduino** [comment]
> What actual physical principle is used as a base for the TRNG ?

Wideband RSSI measurement is used to locally generate a random number. The LSB of each measurement is put through a von Neumann extractor to produce a uniform output.

Semtech uses this for LoRaWAN, which requires AES encryption.

**Comment by Kongduino** [comment]
Not exactly the most scintillating message... What exactly went wrong?

**Comment by FoamyGuy** [comment]
@Kongduino if you mean the checks message this the most relevant sections:
```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/runner/work/Adafruit_CircuitPython_RFM9x/Adafruit_CircuitPython_RFM9x/adafruit_rfm9x.py
All done! ✨ 🍰 ✨
1 file reformatted, 12 files left unchanged.

************* Module adafruit_rfm9x
adafruit_rfm9x.py:872:0: C0301: Line too long (107/100) (line-too-long)
adafruit_rfm9x.py:867:4: C0103: Method name "setupLoRandom" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:879:4: C0103: Method name "resetLoRa" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:889:4: C0103: Method name "getRandomNumber" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:906:4: C0103: Method name "stockupRandom" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:910:8: C0103: Variable name "finalBuff" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:911:8: C0103: Variable name "ix" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:915:12: C0103: Variable name "ix" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
adafruit_rfm9x.py:906:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
adafruit_rfm9x.py:113:0: R0904: Too many public methods (24/20) (too-many-public-methods)

```
The Black code formatter needs to be run, and pylint found a few things to change, mostly the names of variables should use lower case and snake_case with underscores between words instead of capitals with camelCase.

We have a guide that covers how to set up and run these tools locally so you can check the output from them: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code This page covers pre-commit which is the easiest way to run all checks at once. The next few pages in the same guide cover Black and Pylint individually.

**Comment by Kongduino** [comment]
@FoamyGuy Thanks. I was wondering whether there was a bug in the code – which would have been surprising since it works as is. Besides R1710 , which seems like a legit concern, I see the rest is just questionable formatting rules.

**Comment by FoamyGuy** [comment]
@Kongduino Indeed pylint errors typically do not mean that the code won't work, just that it does not follow what are considered best practice for naming and formatting rules. I don't always agree with them either so I understand your hesitation. We use it in order to keep some consistency across the hundreds of CircuitPython libraries in order to make maintenance and documentation over time easier.

I think the functionality that you've added is great and would love to see it included in the library. I will fork from your branch and fix up the pylint errors and submit a new PR so that we can still include this functionality. Thank you for taking the time to implement this and sharing it!

**Comment by Kongduino** [comment]
Thanks a lot for your help. :-)

**Pull request closed without merging**
